application: jasonaroldhomepage
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*.(gif|png|jpg|ico|js|css|pdf|html))
  static_files: \1
  upload: (.*.(gif|png|jpg|ico|js|css|pdf|html))

- url: /
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: "2.5.2"
